### Config MS
spring.application.name=ms-pi-eureka-server
server.port=8761

### Eureka Server
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.server.renewal-percent-threshold=0.85
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.server.enable-self-preservation=true