### Config MS
spring.application.name=ms-pi-apigateway-server
server.port=8080
# Locator
spring.main.allow-bean-definition-overriding=true
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# Route: ms-pd-customer
spring.cloud.gateway.server.webflux.routes[0].id=ms-pd-customer
spring.cloud.gateway.server.webflux.routes[0].uri=lb://ms-pd-customer
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/customers/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=PrefixPath=/rest/v1
# Route: ms-pd-product
spring.cloud.gateway.server.webflux.routes[1].id=ms-pd-product
spring.cloud.gateway.server.webflux.routes[1].uri=lb://ms-pd-product
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/products/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=PrefixPath=/rest/v1
# Route: ms-pd-transaction
spring.cloud.gateway.server.webflux.routes[2].id=ms-pd-transaction
spring.cloud.gateway.server.webflux.routes[2].uri=lb://ms-pd-transaction
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/transactions/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=PrefixPath=/rest/v1

### Eureka Server
eureka.client.enabled=true
eureka.client.service-url.defaultZone=${EUREKA_SERVER:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.healthcheck.enabled=true
# Network
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
spring.cloud.inetutils.preferred-networks=127.0.0
spring.cloud.inetutils.ignored-interfaces=docker0,veth.*,VMware.*,VirtualBox.*,eth0,wlan0
# Management and Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=ALWAYS
management.info.env.enabled=true

### Logging
# Self
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG
# Networks
logging.level.org.springframework.cloud.commons.util.InetUtils=ERROR
# Cache Caffeine
logging.level.org.springframework.cloud.loadbalancer.config.LoadBalancerCacheAutoConfiguration$LoadBalancerCaffeineWarnLogger=ERROR

### Custom Properties
custom.schema=http://localhost:${server.port}