### Config MS
spring.application.name=ms-pi-apigateway-server
server.port=8080

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.fail-fast=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Route: ms-pd-customer
spring.cloud.gateway.server.webflux.routes[0].id=ms-pd-customer
spring.cloud.gateway.server.webflux.routes[0].uri=lb://ms-pd-customer
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/customers/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=PrefixPath=/rest/v1
# Route: ms-pd-product
spring.cloud.gateway.server.webflux.routes[1].id=ms-pd-product
spring.cloud.gateway.server.webflux.routes[1].uri=lb://ms-pd-product
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/products/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=PrefixPath=/rest/v1
# Route: ms-pd-transaction
spring.cloud.gateway.server.webflux.routes[2].id=ms-pd-transaction
spring.cloud.gateway.server.webflux.routes[2].uri=lb://ms-pd-transaction
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/transactions/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=PrefixPath=/rest/v1

# Logging
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG

### Eureka Server
eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.healthcheck.enabled=true
# Management and Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=ALWAYS

### Custom Properties
custom.schema=http://localhost:${server.port}