### MS Rest Transaciton
spring.application.name=ms-pd-transaction

### Config Server
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.enabled=true
spring.cloud.config.name=ms-pd-transaction
spring.cloud.config.profile=default