### Config MS Server
spring.application.name=ms-pi-config-server
server.port=8888

spring.cloud.config.server.git.uri=file:///D:/Dev/workspace-sts/courses/casb--profile-sbc/profile-infra/pi-config-server-repo
spring.cloud.config.server.git.clone-on-start=true
#spring.cloud.config.server.git.force-pull=true
spring.cloud.config.server.git.default-label=master

### Eureka Server
eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.should-enforce-registration-at-init=false
eureka.client.fetch-registry=false
eureka.client.should-fetch-registry-at-init=false
eureka.client.healthcheck.enabled=true
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true

logging.level.com.netflix.discovery.DiscoveryClient=ERROR
logging.level.com.netflix.discovery.InstanceInfoReplicator=OFF
logging.level.com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient=ERROR
logging.level.com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient=OFF

management.endpoints.web.exposure.include=*