### MS Config Server
spring.application.name=ms-pi-config-server
server.port=8888
# Git
spring.cloud.config.server.git.uri=file:///D:/Dev/workspace-sts/courses/casb--profile-sbc/profile-infra/pi-config-server-repo
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.force-pull=true
spring.cloud.config.server.git.default-label=master

### Eureka Server
eureka.client.enabled=true
eureka.client.service-url.defaultZone=${EUREKA_SERVER:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=false
eureka.client.healthcheck.enabled=true
eureka.client.should-enforce-registration-at-init=false
eureka.client.initial-instance-info-replication-interval-seconds=20
# Network
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
spring.cloud.inetutils.preferred-networks=127.0.0
spring.cloud.inetutils.ignored-interfaces=docker0,veth.*,VMware.*,VirtualBox.*,eth0,wlan0
# Management and Actuator
management.endpoints.web.exposure.include=health,info,bus-refresh,refresh
management.endpoint.health.show-details=ALWAYS

### Logging
# Networks
logging.level.org.springframework.cloud.commons.util.InetUtils=ERROR
# Multiple Git
logging.level.org.springframework.cloud.config.server.environment.MultipleJGitEnvironmentRepository=ERROR
# Cache Caffeine
logging.level.org.springframework.cloud.loadbalancer.config.LoadBalancerCacheAutoConfiguration$LoadBalancerCaffeineWarnLogger=ERROR
# Empty replicas (only dev when single-node)
logging.level.com.netflix.eureka.cluster.PeerEurekaNodes=ERROR
logging.level.com.netflix.eureka.registry.AbstractInstanceRegistry=ERROR
logging.level.com.netflix.discovery=ERROR
logging.level.com.netflix.discovery.InstanceInfoReplicator=OFF