### MS Admin Server
spring.application.name=ms-pi-admin-server

### Config Server
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.enabled=true
spring.cloud.config.name=ms-pi-admin-server
spring.cloud.config.profile=default