<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.ssdjr2</groupId>
		<artifactId>profile-parent</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>

	<artifactId>profile-infra</artifactId>
	<packaging>pom</packaging>
	<name>profile-infra</name>
	<description>module that contains the infrastructure</description>
	
	<properties>
		<spring-boot-admin.version>3.5.3</spring-boot-admin.version>
	</properties>
	
	<modules>
		<module>pi-config-server</module>
		<module>pi-eureka-server</module>
		<module>pi-apigateway-server</module>
		<module>pi-admin-server</module>
	</modules>
</project>