### Config MS Server
spring.application.name=ms-pi-apigateway-server
server.port=8090

### Config Server
spring.cloud.config.enabled=false

### Eureka Server
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false