### Gateway Server
spring.application.name=ms-pi-apigateway-server
#spring.profiles.active=default
spring.main.allow-bean-definition-overriding=true

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

### Config Server
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.enabled=true
spring.cloud.config.name=ms-pi-apigateway-server
spring.cloud.config.profile=default
spring.cloud.config.fail-fast=true