### Config MS Rest
#spring.profiles.active=default
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.enabled=true
spring.cloud.config.name=ms-pd-product
spring.cloud.config.profile=default